### ISSUE TITLE
Match JSON Data to be used as input in App

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-android-general#1]
http://data.re-publica.de/data/

**Comment by rafalkowalski** [comment]
I think that we have two choices to do this.
we can parse json to current format or we can change reading json  to match above data.

**Comment by mananwason** [comment]
I think it would be better to change the way json is parsed to suit the data available.

**Comment by batraabhishek** [comment]
Since this app is required before 6th May, thus we must focus on reusing as much code as possible. We will maintain the models, view as well as logic. The only logic that we will change is, parsing of json data. JSON data will be parsed from the API mentioned above. Convert it into model objects (Classes present in model folder). And executing queries from model object (obj.generateSql()). I think by this method we will be able to reuse most of the app code. This is my thought. Feel free to suggest your own or alter this.  :)

**Comment by batraabhishek** [comment]
If every one agree on this... then we can divide some work and start making one more awesome app. We need to update artwork and hide fields which we wont be displaying from sessions and tracks

**Comment by mananwason** [comment]
Yeah I agree. I was doing the same @batraabhishek

**Comment by rafalkowalski** [comment]
Also I agree with it. We should create more specific issues to divide work(i.e Improve models where is it necessary)

**Comment by batraabhishek** [comment]
Cool... Lets make sure we don't end up doing same work. Everyone please state the things that needs to be done. In this way anything missed by anyone will be covered, After this we will order things as per priority. Please add your suggestions as comments. I am adding mine in next comment

**Comment by rafalkowalski** [comment]
1. Improving Models
(Subtasks)
-Speaker
-Sessions
-Map
-Tracks
-locations
2. Improving parsing json(required to divide it to small subtasks)
3. Writing new views where is it nececessary

**Comment by batraabhishek** [comment]
@mariobehling Can you share some artworks, incase of there are some :)

**Comment by batraabhishek** [comment]
Here is some tasks that need to be done from my side
1) High Priority : Map API data to App Model
2) High Priority : Update Artwork and theme
3) Low Priority : Saving user email (from Account Manager), no need to implement 
4) Low Prioirty : Background Parsing of data

Once we are done, we can focus on following things

5) Low Priority : Improving Models (suggested by @rafalkowalski )
6) Low Priority : Adding more views. (suggested by @rafalkowalski )

**Comment by batraabhishek** [comment]
@mananwason @mariobehling @rafalkowalski I am starting with mapping api to app model. FYI

**Comment by championswimmer** [comment]
In the map fragment, how about we put a photo view for the area map (i.e.
this https://re-publica.de/en/map-area )
The directions button takes us to Google Maps to show the way to the venue
already.

=======================================
  Arnav Gupta (championswimmer)
  LinkedIn <http://in.linkedin.com/in/arnavgupta/> | Web
<http://championswimmer.in> | Blog <http://blog.championswimmer.in> |
Twitter <http://twitter.com/championswimmer> | Facebook
<http://facebook.com/championswimmer> | Github
<http://github.com/championswimmer>

**Comment by mananwason** [comment]
@championswimmer this was how it was done earlier. We intentionally made the map fragment to make the map dynamic.

**Comment by mananwason** [comment]
@batraabhishek what all have you done? If  you haven't mapped all data,I suggest we split as I have also done some work towards this already .

**Comment by batraabhishek** [comment]
@mananwason  Cool. On which part you are working on? I can also take some other task. I havn't started on mapping yet

**Comment by mananwason** [comment]
@batraabhishek I have started mapping the speaker data from the speaker json file. What I don't get is that what different is there in the alles json file. Are these the tracks?

**Comment by batraabhishek** [comment]
@mananwason Alles means everything in German (as per Google ;) ). Alles API consist of all the data including sessions, speakers etc
 
![screen shot 2015-05-02 at 9 45 37 am](https://cloud.githubusercontent.com/assets/3257840/7439881/0ca46170-f0b0-11e4-924b-dec4fc9d57c6.png)

**Comment by mananwason** [comment]
Oh !! thanks @batraabhishek Then I am working on speakers and  tracks right now.

**Comment by batraabhishek** [comment]
@mananwason Great, Then I will take Session (Events)

**Comment by mananwason** [comment]
Great !! (y)

**Comment by batraabhishek** [comment]
@mananwason I have almost completed the parsing as sessions were linked together. Please add your changes to improve over mine . Thanks :)

**Comment by championswimmer** [comment]
Whats the common consensus on how we do map?

There are existing interior maps which are PNGs. I don't think we can use
Google Maps for interior.anyway. For directions I have already set the
latitude and longitude so that it uses Google Maps.

**Comment by batraabhishek** [comment]
@championswimmer I am fine with both :)

**Comment by mananwason** [comment]
Me too !! But do you have an internal map ??

**Comment by championswimmer** [comment]
Yeah there are these on the website

https://re-publica.de/en/map-area

**Comment by mananwason** [comment]
I think these maps are too confusing, so instead you can put it in a different activity.

**Comment by mananwason** [comment]
@batraabhishek Why is the app not showing data, even if the database is working. Have you stopped showing the data intentionally?

**Comment by batraabhishek** [comment]
Try relaunching the app. The app is downloading the data in the background.

*Sent via a really tiny keyboard - please excuse the brevity of the message

**Comment by mananwason** [comment]
Yes I see that the data is being downloaded but nothing is shown. I was curious as to why this is happening?

**Comment by championswimmer** [comment]
did the interior maps and directions both.

=======================================
  Arnav Gupta (championswimmer)
  LinkedIn <http://in.linkedin.com/in/arnavgupta/> | Web
<http://championswimmer.in> | Blog <http://blog.championswimmer.in> |
Twitter <http://twitter.com/championswimmer> | Facebook
<http://facebook.com/championswimmer> | Github
<http://github.com/championswimmer>
