### ISSUE TITLE
Create ViewModel for Profile Fragment

### ISSUE THREAD

**Issue by nikit19** [fossasia/open-event-android-general#22]
I would like to work on it
Parent issue https://github.com/fossasia/open-event-android-general/issues/21

**Comment by iamareebjamal** [comment]
First create a service layer, then use it in VM

**Comment by nikit19** [comment]
I am a little confused. Can't we directly use it in VM?
I don't see many components that can be added to the VM from this class.
AFAIK we can only add components which do not depend on context,activity etc
So what I was thinking of doing was declaring the variables in the VM and accessing them from the fragment. Is there anything else that can be done ?

**Comment by iamareebjamal** [comment]
Yes, we need to create services and repository or else the same repetitive code like `SharedPreferenceUtils,get(TOKEN)` will just get transferred from Activities to ViewModels. In fact it won't be possible without services to create android free VMs

VMs are glue logic, they use Models, models should be the components to contain logic, not ViewModel. ViewModel should just bind models and views. This is by definition explanation of VMs

Look at Orga App code for example

**Comment by iamareebjamal** [comment]
Also, this is not true that you can only add logic which does not depend on Android in ViewModels, this entire notion is the reason there are half-baked MV* apps out there. You create components which encapsulate the logic separate from activities and use them in VMs

There needs to be no code in Activities other than view UI logic

**Comment by simarsingh24** [comment]
@iamareebjamal I was also going to start working on Parent issue #21, just wanted to confirm that by Orga App you mean MVP architecture? they are using presenter classes
Please correct me if I am wrong 👍

**Comment by iamareebjamal** [comment]
I wanted to address the architecture beyond MVP and MVVM. What you use in presentation logic is irrelevant to the underlying architecture. It's just a pattern. Real abstraction and encapsulation happens in models which are common in both

MVP

```Kotlin

authModel.login()
   .subscribe(result -> view.onResult(result)
```

MVVM
```Kotlin

fun login() = authModel.login()
```

There's practically no difference. The real effort and elegance lies in creation of AuthModel. Your presenters and ViewModels should be clean as well or you'll just change God Acticities to God ViewModels. Follow SOLID and have only binding and glue logic in the ViewModels. The ViewModels should look like you're using an elegant library with nice API when querying the models, hence holding all logic in isolated components

**Comment by nikit19** [comment]
@iamareebjamal seeing this article https://developer.android.com/jetpack/docs/guide
I think we have to add a repository layer along with the viewModel. Similar to how it is being done here ?

**Comment by iamareebjamal** [comment]
Yup. But no need to add Resource and other jargon. Just isolate the logic in it. Right now I'm working on structuring the project. Continue on this once I have pushed. Work on features and other issues for now
