### ISSUE TITLE
make events cards clickable 

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-android-general#28]
selecting event card should open details of that event
working on it 👍

**Comment by dreadpool2** [comment]
@simarsingh24 Can I help you on this issue?

**Comment by simarsingh24** [comment]
@dreadpool2 you can tweak the UI later

**Comment by dreadpool2** [comment]
Sure :+1:

**Comment by iamareebjamal** [comment]
What's the status? This is the next in line issue as possible to be solved currently

**Comment by simarsingh24** [comment]
will send the PR by today
