### ISSUE TITLE
refactor of orgaApp derrived functions

### ISSUE THREAD

**Issue by simarsingh24** [fossasia/open-event-android-general#61]
<img width="489" alt="screen shot 2018-06-03 at 12 04 24 am" src="https://user-images.githubusercontent.com/16715499/40879724-caadabf6-66c1-11e8-8dc2-7565019b1b3c.png">
<img width="538" alt="screen shot 2018-06-03 at 12 04 33 am" src="https://user-images.githubusercontent.com/16715499/40879725-cbf2f430-66c1-11e8-85dc-1acc60029b61.png">

@iamareebjamal these should be refactored right?

**Comment by nikit19** [comment]
This is not derived from the orga app.
I made these changes in a PR #55 
This functions opens the orga app if it installed else opens it up in playstore
